#!/bin/sh

#  languages or environments to setup
ZL_LANGUAGES="en fr ja"

#  set mirrors etc.
lb config noauto \
    --apt-http-proxy "http://localhost:3142" \
    --parent-mirror-bootstrap "http://ftp.jp.debian.org/debian/" \
    --parent-mirror-binary "http://ftp.jp.debian.org/debian/" \
    --mirror-bootstrap "http://ftp.jp.debian.org/debian/" \
    --mirror-binary "http://ftp.jp.debian.org/debian/" \
    --mirror-chroot "http://ftp.jp.debian.org/debian/" \
    --parent-archive-areas "main contrib non-free" \
    --archive-areas "main contrib non-free" \
    --firmware-chroot true \
    --distribution wheezy \
    --linux-flavours amd64 \
    --binary-images hdd \
    --backports true \
    --bootappend-live "boot=live config persistence quiet splash noeject live-config.utc=no" \
    "${@}"

#
#  adding package lists and local hooks for localization
#
for _LANG in ${ZL_LANGUAGES}
do
    for _FILE in $(find config/package-lists/ -name "*.list.chroot.${_LANG}")
    do
	cp -i "${_FILE}" \
	    "${_FILE%.list.chroot.${_LANG}}_l10n-${_LANG}.list.chroot"
    done

    for _FILE in $(find config/hooks/ -name "*.chroot.${_LANG}")
    do
	cp -i "${_FILE}" "${_FILE%.chroot.${_LANG}}_l10n-${_LANG}.chroot"
    done

    for _FILE in $(find config/hooks/ -name "*.binary.${_LANG}")
    do
	cp -i "${_FILE}" "${_FILE%.binary.${_LANG}}_l10n-${_LANG}.binary"
    done
done
