#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2013 Seiji Matsumoto <matsu@johnen.shinshu-u.ac.jp>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

User_setup_custom ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/adduser.list ]
	then
		return
	fi

	echo -n " user-setup-custom"

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	Configure_user_setup_custom
}

Configure_user_setup_custom ()
{
	# Checking if package is already configured differently
	if [ ! grep -q "^${LIVE_USERNAME}:" /etc/passwd ] 
	then
		return
	fi

	if grep -q "^dialout:" /etc/group
	then
		/usr/sbin/adduser "${LIVE_USERNAME}" dialout
	fi

	if ! grep -q "^plugdev:" /etc/group
	then
		return
	fi

	if ! grep "^plugdev:" /etc/group | grep -q ${LIVE_USERNAME}
	then
		/usr/sbin/adduser "${LIVE_USERNAME}" plugdev
	fi
}

User_setup_custom
